// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using System;
using KD.Dova.Natives;
using System.Security;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KD.Dova.Proxy.Natives
{
    public unsafe struct JavaVM_
    {
        public JNIInvokeInterface_* functions;
    }
}
