// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using System;

namespace KD.Dova.Natives.Structures
{
    internal unsafe struct JavaVMInitArgs
    {
        public IntPtr version;
        public IntPtr nOptions;
        public JavaVMOption options;
        public IntPtr ignoreUnrecognized;
    }
}
