// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using System;
using System.Security;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KD.Dova.Natives.Structures
{
    internal unsafe struct JNIInvokeInterface_
    {
        public IntPtr reserved0;
        public IntPtr reserved1;
        public IntPtr reserved2;

        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr DestroyJavaVM(JavaVM_ vm);
        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr AttachCurrentThread(JavaVM_ vm, out IntPtr penv, IntPtr args);
        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr DetachCurrentThread(JavaVM_ vm);
        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr GetEnv(JavaVM_ vm, out IntPtr penv, IntPtr version);
        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr AttachCurrentThreadAsDaemon(JavaVM_ vm, out IntPtr penv, IntPtr args);
    }
}
