// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using KD.Dova.Core;
using KD.Dova.Utils;
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

namespace KD.Dova.Natives
{
    internal unsafe struct JavaVMAttachArgs
    {
        public int version;
        public IntPtr name;
        public IntPtr group;
    }
}
