// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using KD.Dova.Core;
using KD.Dova.Utils;
using System;
using System.Security;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KD.Dova.Natives
{
    internal unsafe struct JavaVM_
    {
        public JNIInvokeInterface_* functions;
    }
}
