// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using System;

namespace KD.Dova.Proxy.Natives
{
    internal static class JNIConstants
    {
        public static readonly int JNI_FALSE = 0;
        public static readonly int JNI_TRUE = 1;
        public static readonly int JNI_OK = 0 /*  success  */;
        public static readonly int JNI_ERR = (-1) /*  unknown error  */;
        public static readonly int JNI_EDETACHED = (-2) /*  thread detached from the VM  */;
        public static readonly int JNI_EVERSION = (-3) /*  JNI version error  */;
        public static readonly int JNI_ENOMEM = (-4) /*  not enough memory  */;
        public static readonly int JNI_EEXIST = (-5) /*  VM already created  */;
        public static readonly int JNI_EINVAL = (-6) /*  invalid arguments  */;
        public static readonly int JNI_COMMIT = 1;
        public static readonly int JNI_ABORT = 2;
        public static readonly int JDK1_2;
        public static readonly int JDK1_4;
        public static readonly int JNI_VERSION_1_1 = 0x00010001;
        public static readonly int JNI_VERSION_1_2 = 0x00010002;
        public static readonly int JNI_VERSION_1_4 = 0x00010004;
        public static readonly int JNI_VERSION_1_6 = 0x00010006;
        public static readonly int JNI_VERSION_1_8 = 0x00010008;
    }
}
