// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using System;
using KD.Dova;
using System.Security;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KD.Dova.Proxy.Natives
{
    internal unsafe struct JNIInvokeInterface
    {
        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr DestroyJavaVM(JavaVM_ vm);

        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr AttachCurrentThread(JavaVM_ vm, out IntPtr penv, IntPtr args);

        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr DetachCurrentThread(JavaVM_ vm);

        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr GetEnv(JavaVM_ vm, out IntPtr penv, IntPtr version);

        [UnmanagedFunctionPointer(CallingConvention.Winapi)]
        [SuppressUnmanagedCodeSecurity]
        public delegate IntPtr AttachCurrentThreadAsDaemon(JavaVM_ vm, out IntPtr penv, IntPtr args);

    }

    [StructLayout(LayoutKind.Sequential), NativeCppClass]
    internal unsafe struct JNIInvokeInterface_
    {
        public IntPtr reserved0;
        public IntPtr reserved1;
        public IntPtr reserved2;

        public IntPtr DestroyJavaVM;
        public IntPtr AttachCurrentThread;
        public IntPtr DetachCurrentThread;
        public IntPtr GetEnv;
        public IntPtr AttachCurrentThreadAsDaemon;
    }

    internal unsafe class JavaVirtualMachine
    {
        public IntPtr JVM { get; private set; }
        public JNIInvokeInterface_ InvokeInterface { get; private set; }

        internal JavaVirtualMachine(IntPtr jvm)
        {
            this.JVM = jvm;
            this.InvokeInterface = *(*(JavaVM_*)jvm.ToPointer()).functions;
        }

        public IntPtr DestroyJavaVM(JavaVM_ vm) 
        {
            if (destroyJavaVM == null)
            {
                NativeHelper.GetDelegateForFunctionPointer(this.InvokeInterface.DestroyJavaVM, ref destroyJavaVM);
            }
            var ret = destroyJavaVM.Invoke(vm);
            return ret;
        }

        public IntPtr AttachCurrentThread(JavaVM_ vm, out IntPtr penv, IntPtr args) 
        {
            if (attachCurrentThread == null)
            {
                NativeHelper.GetDelegateForFunctionPointer(this.InvokeInterface.AttachCurrentThread, ref attachCurrentThread);
            }
            var ret = attachCurrentThread.Invoke(vm, out penv, args);
            return ret;
        }

        public IntPtr DetachCurrentThread(JavaVM_ vm) 
        {
            if (detachCurrentThread == null)
            {
                NativeHelper.GetDelegateForFunctionPointer(this.InvokeInterface.DetachCurrentThread, ref detachCurrentThread);
            }
            var ret = detachCurrentThread.Invoke(vm);
            return ret;
        }

        public IntPtr GetEnv(JavaVM_ vm, out IntPtr penv, IntPtr version) 
        {
            if (getEnv == null)
            {
                NativeHelper.GetDelegateForFunctionPointer(this.InvokeInterface.GetEnv, ref getEnv);
            }
            var ret = getEnv.Invoke(vm, out penv, version);
            return ret;
        }

        public IntPtr AttachCurrentThreadAsDaemon(JavaVM_ vm, out IntPtr penv, IntPtr args) 
        {
            if (attachCurrentThreadAsDaemon == null)
            {
                NativeHelper.GetDelegateForFunctionPointer(this.InvokeInterface.AttachCurrentThreadAsDaemon, ref attachCurrentThreadAsDaemon);
            }
            var ret = attachCurrentThreadAsDaemon.Invoke(vm, out penv, args);
            return ret;
        }

        public JNIInvokeInterface.DestroyJavaVM destroyJavaVM;
        public JNIInvokeInterface.AttachCurrentThread attachCurrentThread;
        public JNIInvokeInterface.DetachCurrentThread detachCurrentThread;
        public JNIInvokeInterface.GetEnv getEnv;
        public JNIInvokeInterface.AttachCurrentThreadAsDaemon attachCurrentThreadAsDaemon;

    }
}
