// This file has been machine generated.
// Generated by: KD.Dova.Generator
// For more information go to: https://github.com/Sejoslaw/KD.Dova


using KD.Dova.Core;
using KD.Dova.Utils;
using System;

namespace KD.Dova.Natives
{
    internal enum jobjectRefType
    {
        JNIInvalidRefType = 0,
        JNILocalRefType = 1,
        JNIGlobalRefType = 2,
        JNIWeakGlobalRefType = 3
    }
}
